runtime: python310  # Use Python 3.10
env: standard       # Use the standard environment

entrypoint: gunicorn -b :$PORT main:app  # Use gunicorn as the WSGI server

handlers:
- url: /.*
  script: auto      # Let App Engine handle routing automatically

# Optional: Define environment variables
env_variables:
  FLASK_ENV: production
