steps:
  # Install dependencies
  - name: 'python:3.10'
    id: 'Install dependencies'
    entrypoint: pip
    args: ['install', '-t', '.', '-r', 'requirements.txt']

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    id: 'Deploy to App Engine'
    args: ['app', 'deploy']

  # Specify a logs bucket
  options:
    logging: CLOUD_LOGGING_ONLY  # Use Cloud Logging for build logs
    
  # Timeout for the build process (optional)
  timeout: '1600s'

# Artifacts to store after the build (optional)
#artifacts:
  #objects:
    #location: 'gs://your-bucket-name/'
    #paths: ['app.yaml', 'main.py', 'requirements.txt']
    
